# -*- coding: utf-8 -*-
"""data_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7lvVq8LAoJ1BXxPJAWFeH1yeccMDbWr
"""

import pandas as pd

"""# Fund Master Data loading"""

FM_df = pd.read_csv('01_fund_master.csv')

FM_df.head()

FM_df.shape

"""- Fund Master dataset contains 40 rows and 15 columns"""

FM_df.dtypes

"""# nav history data loading"""

nav_df = pd.read_csv('02_nav_history.csv')

nav_df.head()

nav_df.shape

"""The dataset contains 46000 rows and 3 coumns"""

nav_df.dtypes

"""# aum by fund house data loading"""

aum_df = pd.read_csv('03_aum_by_fund_house.csv')

aum_df.head()

aum_df.shape

"""The data set contains 90 rows and 5 columns"""

aum_df.dtypes

"""# Monthly SIP inflow Data loading"""

SIP_df = pd.read_csv('04_monthly_sip_inflows.csv')

SIP_df.head()

SIP_df.shape

"""The dataset contains of 48 rows and 6 columns"""

SIP_df.dtypes

"""# Category Inflow Data loading"""

Cat_df = pd.read_csv('05_category_inflows.csv')

Cat_df.head()

Cat_df.shape

"""The dataset contains of 144 rows and 3 columns"""

Cat_df.dtypes

"""# Industy Folio Data Loading"""

IF_df = pd.read_csv('06_industry_folio_count.csv')

IF_df.head()

IF_df.shape

"""The dataset contains 21 rows and 6 columns"""

IF_df.dtypes

"""# Scheme Performance Data Loading"""

SP_df = pd.read_csv('07_scheme_performance.csv')

SP_df.head()

SP_df.shape

"""The dataset contains of 40 rows and 19 columns."""

SP_df.dtypes

"""# Investors Transactions Data loading"""

IT_df = pd.read_csv('08_investor_transactions.csv')

IT_df.head()

IT_df.shape

"""This dataset contains of 32778 rows and 13 columns"""

IT_df.dtypes

"""# Portfoilio Holdings Data loading"""

PH_df = pd.read_csv('09_portfolio_holdings.csv')

PH_df.head()

PH_df.shape

"""The dataset consists of 322 rows and 8 columns"""

PH_df.dtypes

"""# Benchmark indices Data loading"""

BI_df = pd.read_csv('10_benchmark_indices.csv')

BI_df.head()

BI_df.shape

"""The dataset consits of 8050 rows and 3 columns"""

BI_df.dtypes