# -*- coding: utf-8 -*-
"""live_nav_fetch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jHi7Y1RyFvqDa2tqkx9z7WlGxDOjfsDT
"""

import csv
import json

file_path = "118632.json"


with open(file_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)


meta_info = raw_data.get("meta", {})
nav_data = raw_data.get("data", [])


nav_csv_file = "Nippon_Large_Cap_nav_data.csv"
if nav_data:

    nav_headers = nav_data[0].keys()

    with open(nav_csv_file, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=nav_headers)
        writer.writeheader()
        writer.writerows(nav_data)

    print(f"Main NAV records successfully saved to: {nav_csv_file}")

file_path = "119092.json"


with open(file_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)


meta_info = raw_data.get("meta", {})
nav_data = raw_data.get("data", [])


nav_csv_file = "Axis_Bluechip_nav_data.csv"
if nav_data:

    nav_headers = nav_data[0].keys()

    with open(nav_csv_file, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=nav_headers)
        writer.writeheader()
        writer.writerows(nav_data)

    print(f"Main NAV records successfully saved to: {nav_csv_file}")

file_path = "119551.json"


with open(file_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)


meta_info = raw_data.get("meta", {})
nav_data = raw_data.get("data", [])


nav_csv_file = "SBI_Bluechip_nav_data.csv"
if nav_data:

    nav_headers = nav_data[0].keys()

    with open(nav_csv_file, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=nav_headers)
        writer.writeheader()
        writer.writerows(nav_data)

    print(f"Main NAV records successfully saved to: {nav_csv_file}")

file_path = "120503.json"


with open(file_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)


meta_info = raw_data.get("meta", {})
nav_data = raw_data.get("data", [])


nav_csv_file = "ICICi_Bluechip_nav_data.csv"
if nav_data:

    nav_headers = nav_data[0].keys()

    with open(nav_csv_file, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=nav_headers)
        writer.writeheader()
        writer.writerows(nav_data)

    print(f"Main NAV records successfully saved to: {nav_csv_file}")

file_path = "120841.json"


with open(file_path, "r", encoding="utf-8") as f:
    raw_data = json.load(f)


meta_info = raw_data.get("meta", {})
nav_data = raw_data.get("data", [])


nav_csv_file = "Kotak_Bluechip_nav_data.csv"
if nav_data:

    nav_headers = nav_data[0].keys()

    with open(nav_csv_file, mode="w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=nav_headers)
        writer.writeheader()
        writer.writerows(nav_data)

    print(f"Main NAV records successfully saved to: {nav_csv_file}")